CREATE DATABASE IF NOT EXISTS DBNAME1;
USE DBNAME1;

CREATE TABLE IF NOT EXISTS TABLENAME1 (
        id INT(11) AUTO_INCREMENT,
        description VARCHAR(255),
        PRIMARY KEY (id)
);

INSERT INTO TABLENAME1 VALUE(0, 'HELLO WORLD!');